### PR TITLE
make form appear

### PR DESCRIPTION
**Pull request by bcfuchs**
fixed reset form no show; wrong block name in template. 
However, there are more problems...

### CODE REVIEW

**Comment by bcfuchs** [comment]
fixed html and added bootstrap form css.

**Comment by bcfuchs** [comment]
&lt;/ul&gt; was in wrong position

**Comment by bcfuchs** [comment]
fixed reset done message and added bootstrap forms css to recovery page

**Comment by pooyadav** [comment]
Brian solved this issue as a participant in Mozilla Sprint 2015

**Pull request merged**
